// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RsvpForm.Repositories;

#nullable disable

namespace RsvpForm.Migrations
{
    [DbContext(typeof(RsvpRepository))]
    [Migration("20230728203206_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RsvpForm.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isComing")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Candidate");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 21,
                            Country = "Turkey",
                            FirstName = "Vedat",
                            LastName = "Cinbat",
                            isComing = true
                        },
                        new
                        {
                            Id = 2,
                            Age = 26,
                            Country = "United States",
                            FirstName = "Jack",
                            LastName = "Nickelson",
                            isComing = true
                        },
                        new
                        {
                            Id = 3,
                            Age = 12,
                            Country = "United Kingdom",
                            FirstName = "Oliver",
                            LastName = "Blum",
                            isComing = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
